//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileManagerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class files
    {
        public string fileId { get; set; }
        public string fileName { get; set; }
        public string fileUpploadTime { get; set; }
        public string fileType { get; set; }
        public string inFolderId { get; set; }
        public string fileUrl { get; set; }
        public string fileOwnerId { get; set; }
        public Nullable<int> fileDownloadCount { get; set; }
    
        public virtual folders folders { get; set; }
        public virtual users users { get; set; }
    }
}
