//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileManagerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class folders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public folders()
        {
            this.files = new HashSet<files>();
        }
    
        public string folderId { get; set; }
        public string folderOwnerId { get; set; }
        public string folderName { get; set; }
        public string folderCreateTime { get; set; }
        public string folderGroupLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<files> files { get; set; }
        public virtual users users { get; set; }
    }
}
